export default {
	'left.title': 'Estás a unos pasos de ser parte de Alivia',
	'left.step.first.label': 'SOBRE EL PACIENTE',
	'left.step.second.label': 'CONTACTO',
	'left.step.third.label': 'CONTRASEÑA',
	// About Patient
	'aboutPatient.title.firstSection': 'Llena',
	'aboutPatient.title.secondSection': 'tus datos',
	'aboutPatient.title.thirdSection': 'para continuar',
	'aboutPatient.subTitle': '1. TUS DATOS',
	'aboutPatient.fields.name.label': 'Nombres del paciente',
	'aboutPatient.fields.lastName.label': 'Apellido paterno del paciente',
	'aboutPatient.fields.secondSurname.label': 'Apellido materno del paciente',
	'aboutPatient.fields.birthDate.label': 'Fecha de nacimiento del paciente',
	'aboutPatient.fields.gender.label': 'Sexo del paciente',
	'aboutPatient.privacyPolicy.firstSection': 'Puedes revisar nuestra',
	'aboutPatient.privacyPolicy.secondSection': 'política de privacidad aquí',
	'aboutPatient.submit.text': 'Continuar',
	'aboutPatient.validation.name.required': 'El nombre es obligatorio',
	'aboutPatient.validation.lastName.required': 'El apellido paterno es obligatorio',
	'aboutPatient.validation.secondSurname.required': 'El apellido materno es obligatorio',
	'aboutPatient.validation.birthDate.required': 'La fecha de nacimiento es obligatoria',
	'aboutPatient.validation.gender.required': 'El sexo es obligatorio',
	// Contact Patient
	'contactPatient.title.firstSection': 'Llena tus',
	'contactPatient.title.secondSection': 'datos del contacto',
	'contactPatient.title.thridSection': 'para continuar',
	'contactPatient.subTitle': '2. DATOS DE CONTACTO',
	'contactPatient.fields.id.label': 'DNI o CE del paciente',
	'contactPatient.fields.phoneNumber.label': 'Ingresa un número celular de contacto',
	'contactPatient.fields.phoneNumber.helperText': 'Será necesario para ingresar a tu cuenta',
	'contactPatient.fields.email.label': 'Ingresa un correo de contacto',
	'contactPatient.fields.email.helperText': 'Enviaremos un recordatorio a este correo',
	'contactPatient.fields.address.label': 'Ingresa tu dirección de domicilio actual',
	'contactPatient.fields.address.helperText': 'Con la dirección se emitirá una receta válida',
	'contactPatient.fields.ubigeo.label': 'Ubigeo',
	'contactPatient.fields.ubigeo.helperText': 'Con la dirección se emitirá una receta válida',
	'contactPatient.legalInformation.firstSection': 'Al continuar estás confirmando que estás de acuerdo con nuestra',
	'contactPatient.legalInformation.privacyPolicyLink': 'política de privacidad',
	'contactPatient.legalInformation.secondSection': 'y nuestros',
	'contactPatient.legalInformation.termsAndConditionsLink': 'términos y condiciones',
	'contactPatient.submit.text': 'Continuar',
	'contactPatient.validation.id.required': 'El DNI o CE del paciente es obligatorio',
	'contactPatient.validation.id.digits': 'Ingrese un DNI o CE valido',
	'contactPatient.validation.phoneNumber.required': 'El número de celular de contacto es obligatorio',
	'contactPatient.validation.email.required': 'El correo electrónico es obligatorio',
	'contactPatient.validation.email.validEmail': 'Ingrese un correo de contacto valido',
	// Patient Password
	'patientPassword.title.firstSection': 'Crea tu',
	'patientPassword.title.secondSection': 'contraseña',
	'patientPassword.title.thridSection': 'para acceder a Alivia',
	'patientPassword.subTitle': '3. CONTRASEÑA',
	'patientPassword.fields.password.label': 'Introduce una contraseña',
	'patientPassword.fields.password.helperText': 'Será necesario para ingresar a tu cuenta',
	'patientPassword.fields.repeatPassword.label': 'Repite la contraseña',
	'patientPassword.legalInformation.firstSection': 'Al continuar estás confirmando que estás de acuerdo con nuestra',
	'patientPassword.legalInformation.privacyPolicyLink': 'política de privacidad',
	'patientPassword.legalInformation.secondSection': 'y nuestros',
	'patientPassword.legalInformation.termsAndConditionsLink': 'términos y condiciones',
	'patientPassword.submit.text': 'Finalizar y crear mi cuenta',
	// Success Message
	'successSignUp.title.firstLine': ' tu cuenta ha sido creada',
	'successSignUp.title.secondLine': 'de manera exitosa',
	'successSignUp.continue': 'Ir a mi espacio',
	'successSignUp.appointment': 'Agendar una cita',
	// Welcome Message
	'welcomeSignUp.title.firstLine': ' te damos la bienvenida a Alivia',
};
