const preSignUp = {
	'left.titlePrefix': 'UN SEGUNDO,',
	'left.title.firstLine': 'Necesitamos mas informacion',
	'left.title.secondLine': 'del paciente',
	'right.subTitle.base': 'Indicaste que la consulta es',
	'right.subTitle.toSmeoneElse': 'para alguien más',
	'right.subTitle.toYou': 'para tí',
	'right.subTitle.continueQuestion.mobile': '¿Cómo deseas continuar?',
	'right.signUp.label.toSomeoneElse': 'CRÉALE UNA CUENTA',
	'right.signUp.body.toSomeoneElse': 'Así tendrá un espacio dónde centralizar todas sus consultas.',
	'right.signUp.label.toYou': 'CREAR UNA CUENTA',
	'right.signUp.body.toYou': 'Ten en un sólo espacio toda la inforamación de tus citas.',
	'right.signUp.label.guest': 'CONTINUAR COMO INVITADO',
	'right.signUp.label.guest.mobile': 'INVITADO',
	'right.signUp.body.guest.toSomeoneElse': 'Pediremos los datos del paciente pero no los guardaremos en una cuenta.',
	'right.signUp.body.guest.toYou': 'Pediremos tus datos pero no los guardaremos en una cuenta.',
	'right.signIn.label.toYou': 'INICIAR SESIÓN',
	'right.signIn.body.toYou': 'Ingresa a tu cuenta y accede a tu historial con info de todas tus citas en Alivia.',
	'right.newOwner.label.toSomeoneElse': '¿La consulta es para un pariente?',
	'right.newOwner.link.toSomeoneElse': 'Si es así, haz clic acá',
	'right.newOwner.label.toYou': '¿La consulta en realidad es para ti?',
	'right.newOwner.link.toYou': 'Ingresa acá',
	'right.signIn.label.toSomeoneElse': '¿El paciente ya tiene una cuenta?',
	'right.signIn.link.toSomeoneElse': 'Inicia sesión',
};

export default preSignUp;
