image: node:10.20.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - mkdir .cache_yarn && cd ./.cache_yarn

stages:
  - install
  - build
  - deploy
install_stage:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  artifacts:
    paths:
    - node_modules/
  only:
    - dev
    - master

build_stage_dev:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_DEV"
  script:
    - yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - dev
deploy_stage_dev:
  stage: deploy
  only:
    - dev
  script:
    - yarn global add firebase-tools --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_DEV -P default

build_stage_prod:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_PROD"
  script:
    - yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - master

deploy_stage_dev:
  stage: deploy
  only:
    - master
  script:
    - yarn global add firebase-tools --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_DEV -P prod