image: node:10.20.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - mkdir .cache_yarn && cd ./.cache_yarn

stages:
  - install
  - build
  - deploy
install_stage:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  artifacts:
    paths:
    - node_modules/
  only:
    - dev
    - staging
    - master

build_stage_dev:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_DEV"
    REACT_APP_CULQI_PK_KEY: "$CULQI_PK_KEY_DEV"
    REACT_APP_CONFERENCE_URL: "$CONFERENCE_BASE_URL_DEV"
    REACT_APP_GOOGLE_MAPS_KEY: "$GOOGLE_MAPS_KEY_DEV"
    REACT_APP_UGO_API_URL: "$UGO_API_URL_DEV"
    REACT_APP_KUSHKI_MERCHANT_ID: "$KUSHKI_MERCHANT_ID_DEV"
    REACT_APP_KUSHKI_IN_TEST_ENV: "$KUSHKI_IN_TEST_ENV_DEV"
    REACT_APP_KUSHKI_LINK_DOWNLOAD_PDF: "$KUSHKI_LINK_DOWNLOAD_PDF_DEV"
    REACT_APP_LOGO_URL: '$REACT_APP_LOGO_URL_DEV'
  script:
    - yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - dev
deploy_stage_dev:
  stage: deploy
  only:
    - dev
  script:
    - yarn global add firebase-tools@9.20.0 --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_DEV -P default

build_stage_staging:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_STAGE"
    REACT_APP_CULQI_PK_KEY: "$CULQI_PK_KEY_DEV"
    REACT_APP_CONFERENCE_URL: "$CONFERENCE_BASE_URL_DEV"
    REACT_APP_GOOGLE_MAPS_KEY: "$GOOGLE_MAPS_KEY_DEV"
    REACT_APP_UGO_API_URL: "$UGO_API_URL_STAGE"
    REACT_APP_KUSHKI_MERCHANT_ID: "$KUSHKI_MERCHANT_ID_DEV"
    REACT_APP_KUSHKI_IN_TEST_ENV: "$KUSHKI_IN_TEST_ENV_DEV"
    REACT_APP_KUSHKI_LINK_DOWNLOAD_PDF: "$KUSHKI_LINK_DOWNLOAD_PDF_DEV"
    REACT_APP_LOGO_URL: '$REACT_APP_LOGO_URL_DEV'
  script:
    - yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - staging

deploy_stage_staging:
  stage: deploy
  only:
    - staging
  script:
    - yarn global add firebase-tools --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_DEV -P pacientes-stage    

build_stage_prod:
  stage: build
  variables:
    REACT_APP_BASE_URL: "$API_BASE_URL_PROD"
    REACT_APP_CULQI_PK_KEY: "$CULQI_PK_KEY_PROD"
    REACT_APP_CONFERENCE_URL: "$CONFERENCE_BASE_URL_PROD"
    REACT_APP_GOOGLE_MAPS_KEY: "$GOOGLE_MAPS_KEY_PROD"
    REACT_APP_UGO_API_URL: "$UGO_API_URL_PROD"
    REACT_APP_KUSHKI_MERCHANT_ID: "$KUSHKI_MERCHANT_ID_PROD"
    REACT_APP_KUSHKI_IN_TEST_ENV: "$KUSHKI_IN_TEST_ENV_PROD"
    REACT_APP_KUSHKI_LINK_DOWNLOAD_PDF: "$KUSHKI_LINK_DOWNLOAD_PDF_PROD"
    REACT_APP_LOGO_URL: '$REACT_APP_LOGO_URL_PROD'

  script:
    - yarn build
  dependencies:
    - install_stage
  artifacts:
    paths:
    - build/
  only:
    - master

deploy_stage_prod:
  stage: deploy
  only:
    - master
  script:
    - yarn global add firebase-tools --cache-folder ./.cache_yarn
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY_DEV -P prod
