const clinicalExamination = {
	'left.titlePrefix': 'AHORA,',
	'left.title.firstLine': 'Tus exámenes clínicos',
	'left.title.secondLine': 'desde Alivia',
	'left.button.continue': 'Continuar',
	'contactPatient.subTitle': 'Algunos datos Sobre el paciente',
	'contactPatient.fields.id.label': 'DNI o CE del paciente',
	'contactPatient.fields.name.label': 'Nombres y Apellidos del paciente',
	'contactPatient.fields.phoneNumber.label': 'ingrese un número de celular de contacto',
	'contactPatient.fields.email.label': 'ingrese un correo de contacto',
	'contactPatient.fields.adress.label': 'Dirección del cliente',
	'contactPatient.addressReference.label': 'Piso, puerta, oficina o referencia',
	'contactPatient.legalInformation.privacyPolicyLink': 'Autorizo transferir mi información al laboratorio',
	'left.button.pago': 'Pagar',
	'contactPatient.submit.text': 'Siguiente',
	'left.button.agendar': 'Agendar',
	'right.default.title': 'Elegir Modalidad.',
	'examen.typeExam': 'Elige el tipo de exámen que deseas realizar',
	'steps.firstStep.label': 'ELIGE EL EXÁMEN',
	'steps.secondStep.label': 'ELIGE EL LABORATORIO',
	'steps.thirdStep.label': 'CONFIRMAR AGENDAMIENTO',
	'left.label.modalidad': 'Modalidad',
	'right.label.calle': 'Calle las almendras 261, La Molina',
	'right.modality.edit': 'Editar',
	'right.modality.Fecha': 'FECHA',
	'aboutme.submit.text': 'Continuar',
	'left.label.exams': 'LOS EXÁMENES A REALIZAR SON:',
	'left.label.dateLaboratory': 'Selecciona la <strong>fecha</strong> y <strong>laboratorio</strong>',
};

export default clinicalExamination;
