const selectDoctor = {
	'left.titlePrefix': 'AHORA,',
	'left.title.firstLine': 'Selecciona al doctor/a',
	'left.title.secondLine': 'y horario ideal.',
	'left.button.continue': 'Continuar',
	'right.title': 'Selecciona la <strong>fecha</strong> y <strong>doctor</strong>',
	'right.dateLabel': 'FECHA:',
	'right.useCaseLabel': 'ESPECIALIDAD:',
	'right.appointmentCostLabel': 'COSTO DE CONSULTA:',
	'right.foundDoctors': 'TENEMOS {{doctors}}',
	'right.availableDoctors.title': 'ELIGE UN HORARIO:',
	'right.availableDoctors': 'DOCTOR DISPONIBLE',
	'right.availableDoctors_plural': 'DOCTORES DISPONIBLES', // eslint-disable-line
	'right.notFoundDoctors': 'NO HAY DOCTORES DISPONIBLES EN LA FECHA SELECCIONADA. POR FAVOR ELIGE OTRA FECHA',
	'right.doctor.prefix': 'Dr(a).',
	'right.doctor.moreInformation': 'SOBRE EL DOCTOR',
	'steps.firstStep.label': 'DOCTOR & HORARIO',
	'steps.secondStep.label': 'REGISTRO',
	'steps.thirdStep.label': 'RESUMEN & PAGO',
	'steps.mobile.firstStep.label': 'SOBRE TI',
	'steps.mobile.secondStep.label': 'DATOS MÉDICOS',
	'steps.mobile.thirdStep.label': 'CONTACTO',
	'warning.modal.title': 'Confirmo que el paciente',
	'warning.modal.dont': 'NO:',
	'warning.modal.firstCondition': '- Es un niño menor de 8 años.',
	'warning.modal.secondCondition': '- Está atravesando un tratamiento oncológico.',
	'warning.modal.thirdCondition': '- Tiene una enfermedad crónica avanzada (ej. Insuficiencia Renal).',
	'warning.modal.fourthCondition': '- Tiene transtornos alimenticios (anorexia o bulimia).',
	'warning.modal.fifthCondition': '- Es un deportista de Alto Rendimiento.',
	'warning.modal.termsFirst': 'Si el paciente presenta algunas de estas condiciones,',
	'warning.modal.termsBold': 'no podremos atenderlo',
	'warning.modal.termsSecond': 'debido a que se requiere un acompañamiento distinto durante el tratamiento.',
	'warning.modal.cancel': 'Cancelar',
	'warning.modal.accept': 'Continuar a agendar cita',
	'selectAppointmentOwner.title': '¿La cita es para ti o para alguien más?',
	'selectAppointmentOwner.for': 'Para',
	'selectAppointmentOwner.me': 'mi',
	'selectAppointmentOwner.someoneElse': 'alguien más',
	'doctorModal.aboutMe.title': 'SOBRE MI:',
	'doctorModal.educationSection.title': 'FORMACIÓN:',
	'doctorModal.diseasesSection.title': 'ENFERMEDADES QUE TRATO:',
	'doctorModal.seeMore': 'VER MÁS',
	'doctorModal.seeLess': 'VER MENOS',
	'doctorModal.seeAvailability': 'Ver disponibilidad',
	'doctorModal.userOpinionsSection.title': 'HISTORIAS DE PACIENTES',
};

export default selectDoctor;
