export default {
	'askAddress.title': 'Necesitamos tu dirección para emitir tu receta médica.',
	'askAddress.title.alternative': 'Necesitamos la dirección para validar si está dentro del área de cobertura.',
	'askAddress.subTitle':
		'Según lo dispuesto por el MINSA, toda receta médica debe tener registrada la dirección del paciente.',
	'askAddress.address.label': 'Ingrese el nombre de Avenida/Calle/Jirón/Pasaje, y seleccione de la lista',
	'askAddress.address.placeholder': 'Ingresa una dirección',
	'askAddress.addressReference.label': 'Piso, interior, puerta, oficina o referencia',
	'askAddress.addressReference.placeholder': 'Ejemplo: puerta 4, oficina 501',
	'askAddress.addressProvince.label': 'Provincia',
	'askAddress.addressProvince.placeholder': 'Ejemplo: Lima',
	'askAddress.addressDistrict.label': 'Distrito',
	'askAddress.addressDistrict.placeholder': 'Ejemplo: Breña',
	'askAddress.addressNumber.label': 'Número, Lote',
	'askAddress.addressNumber.placeholder': 'Ejemplo: 666',
	'askAddress.addressLocation.label':
		'Por favor, ubique su dirección en el mapa, dando click a la posición más aproximada a su domicilio:',
	'askAddress.addressReference.error': 'Debes ingresar una referencia',
	'askAddress.address.error': 'Debe seleccionar una dirección',
	'askAddress.address.name.default': 'Dirección Delivery',
	'askAddress.submitAddress': 'Continuar a ver mi receta',
	'askAddress.addressBenefits.title': 'Beneficios de añadir tu dirección:',
	'askAddress.addressBenefits.firstReason': 'Recibe la cotización de tu receta después de la cita',
	'askAddress.addressBenefits.secondReason': 'Si deseas, podrás recibir los medicamentos sin salir de casa',
	'askAddress.addressBenefits.thirdReason': 'Garantía de calidad avalada por',
	'askAddress.successModal.title': '¡Gracias! Ya puedes ver tu receta médica',
	'askAddress.successModal.body.firstLine': 'Ya está disponible',
	'askAddress.successModal.body.secondLine': 'tu receta médica cotizada.',
	'askAddress.successModal.continue': 'Ver mi receta digital',
	'askAddress.successModal.close': 'Cerrar',
};
