const forgotPassword = {
	'forgotPassword.validateDocument.title': '¿Olvidaste tu contraseña?',
	'forgotPassword.validateDocument.subTitle': 'Primero vamos a verificar tu identidad',
	'forgotPassword.validateDocument.idLabel': 'Número de DNI o CE con el que te registraste:',
	'forgotPassword.validateDocument.nextButton': 'Continuar',
	'forgotPassword.validateOTP.title': 'Verifica que eres tú',
	'forgotPassword.validateOTP.subTitle': 'Te hemos enviado un código al',
	'forgotPassword.validateOTP.otpCodeLabel': 'Ingresa el código de 4 dígitos enviado a tu celular',
	'forgotPassword.validateOTP.otpCodeLabel.mobile': 'Ingresa el código que hemos enviado a tu celular',
	'forgotPassword.validateOTP.nextButton': 'Continuar',
	'forgotPassword.validateOTP.resendCodeLabel': 'Puedes solicitar un nuevo código',
	'forgotPassword.validateOTP.resendCodeLink': 'aquí',
	'forgotPassword.updatePassword.title': 'Nueva contraseña',
	'forgotPassword.updatePassword.subTitle': 'Escriba una contraseña que vayas a recordar',
	'forgotPassword.updatePassword.newPasswordLabel': 'Nueva contraseña',
	'forgotPassword.updatePassword.repeatPasswordLabel': 'Confirmar nueva contraseña',
	'forgotPassword.updatePassword.submitNewPassword': 'Crear nueva contraseña',
	'forgotPassword.validation.id.required': 'El DNI o CE del paciente es obligatorio',
	'forgotPassword.validation.id.digits': 'Ingrese un DNI o CE valido',
	'forgotPassword.validation.id.notFound': 'El DNI o CE del paciente no existe',
	'forgotPassword.validation.otpCode.required': 'El codigo de verificación es obligatorio',
	'forgotPassword.validation.otpCode.digits': 'Ingrese solo números',
	'forgotPassword.validation.otpCode.notFound': 'El codigo de verificación no existe, intenta otra vez',
};

export default forgotPassword;
