const signUp = {
	'left.titlePrefix': 'AHORA,',
	'left.title.toYouOrSomeoneElse': 'Creación de cuenta',
	'left.title.guest': 'Continuar como invitado',
	'left.step.first.label': 'SOBRE EL PACIENTE',
	'left.step.second.label': 'DATOS MÉDICOS',
	'left.step.third.label': 'CONTACTO',
	// About Me
	'aboutme.title.firstSection': 'Llena los',
	'aboutme.title.secondSection': 'datos del paciente',
	'aboutme.title.thirdSection': 'para continuar',
	'aboutme.subTitle.forMe': '1. INFORMACIÓN SOBRE TI',
	'aboutme.subTitle.forSomeoneElse': '3. INFORMACIÓN SOBRE EL PACIENTE',
	'aboutme.fields.name.label': 'Nombre del paciente',
	'aboutme.fields.lastName.label': 'Apellido paterno del paciente',
	'aboutme.fields.secondSurname.label': 'Apellido materno del paciente',
	'aboutme.fields.birthDate.label': 'Fecha de nacimiento del paciente',
	'aboutme.fields.birthDate.placeholder': 'DD/MM/AAAA',
	'aboutme.fields.gender.label': 'Sexo del paciente',
	'aboutme.fields.gender.placeholder': 'Selecciona tu género',
	'aboutme.validation.name.required': 'El nombre del paciente es obligatorio',
	'aboutme.validation.lastName.required': 'El apellido paterno del paciente es obligatorio',
	'aboutme.validation.secondSurname.required': 'El apellido materno del paciente es obligatorio',
	'aboutme.validation.birthDate.required': 'La fecha de nacimiento es obligatoria',
	'aboutme.validation.gender.required': 'El sexo del paciente es obligatorio',
	'aboutme.privacyPolicy.firstSection': 'Estoy de acuerdo con la',
	'aboutme.privacyPolicy.secondSection': 'política de privacidad',
	'aboutme.submit.text': 'Continuar',
	// Medical data
	'medicalData.mobile.title.firstSection': 'Completa esta información médica',
	'medicalData.title.firstSection': 'Completa esta',
	'medicalData.title.secondSection': 'información médica básica',
	'medicalData.title.thirdSection': 'sobre el',
	'medicalData.title.fourthSection': 'paciente para que el doctor te pueda atender mejor.',
	'medicalData.subTitle': '2. DATOS MÉDICOS',
	'medicalData.fields.takeMedicines.label': '¿El paciente toma algún medicamento?',
	'medicalData.fields.medicineList.label': '¿Qué medicamentos?',
	'medicalData.fields.haveAllergies.label': '¿El paciente tiene alguna alergia?',
	'medicalData.fields.allergies.label': '¿Qué alergia es?',
	'medicalData.fields.moreInfo.label': '¿Hay algo más que el doctor deba saber?',
	'medicalData.fields.moreInfo.helperText': 'Dinos si tienes una condición pre-existente/prenatales',
	'medicalData.fields.optional.label': '(opcional)',
	'medicalData.fields.yesOption': 'Sí',
	'medicalData.fields.noOption': 'No',
	'medicalData.validation.takeMedicines.required': 'Responde esta pregunta para continuar',
	'medicalData.validation.medicineList.required': 'Indícale al doctor qué medicamento está tomando',
	'medicalData.validation.haveAllergy.required': 'Responde esta pregunta para continuar',
	'medicalData.validation.allergy.required': 'Indícale al doctor las alergias son',
	'medicalData.privacyPolicy.firstSection': 'Estoy de acuerdo con la',
	'medicalData.privacyPolicy.secondSection': 'política de privacidad',
	'medicalData.submit.text': 'Continuar',
	// Contact
	'contact.mobile.title': 'Usaremos tus datos de contacto para enviarte la información de tu cita',
	'contact.title.firstLine': 'Usaremos los datos de contacto para',
	'contact.title.secondLine': 'enviar información de la cita',
	'contact.subTitle': '3. DATOS DE CONTACTO',
	'contact.fields.id.label.toYou': 'Ingresa tu DNI o CE',
	'contact.fields.id.label.toSomeoneElse': 'DNI o CE del paciente',
	'contact.fields.phoneNumber.label.toYou': 'Ingresa tu número celular',
	'contact.fields.phoneNumber.label.toSomeoneElse': 'Ingresa el número de celular de contacto',
	'contact.fields.phoneNumber.helperText.toYou': 'Con este número iniciarás sesión en el futuro',
	'contact.fields.phoneNumber.helperText.toSomeoneElse': 'Enviaremos un recordatorio a este celular',
	'contact.fields.email.label.toYou': 'Ingresa tu correo electrónico',
	'contact.fields.email.label.toSomeoneElse': 'Ingresa un correo de contacto',
	'contact.fields.email.helperText': 'Enviaremos un recordatorio a este correo',
	'contact.fields.password.label': 'Contraseña',
	'contact.fields.repeatPassword.label': 'Repetir Contraseña',
	'contact.validation.id.required': 'El DNI o CE del paciente es obligatorio',
	'contact.validation.id.digits': 'Ingrese un DNI o CE valido',
	'contact.validation.phoneNumber.required': 'El número de celular de contacto es obligatorio',
	'contact.validation.password.required': 'Ingresa una contraseña',
	'contact.validation.password.incorrectFormat': 'Usa 6 caracteres o más para tu contraseña',
	'contact.validation.repeatPassword.required': 'La contraseña es obligatoria',
	'contact.validation.repeatPassword.notEqual': 'Las contraseñas no coinciden. Intenta de nuevo',
	'contact.validation.email.validEmail': 'Ingrese un correo de contacto valido',
	'contact.legalInformation.firstSection': 'Al crear una cuenta estás confirmando que estás de acuerdo con nuestra',
	'contact.legalInformation.privacyPolicyLink': 'política de privacidad',
	'contact.legalInformation.secondSection': 'y nuestros',
	'contact.legalInformation.termsAndConditionsLink': 'términos y condiciones.',
	'contact.submit.text': 'De acuerdo, deseo ingresar',
	'contact.phoneNumber.error': 'El número que ingresaste es inválido',
	'contact.email.error': 'El email que ingresaste es inválido',
	'contact.fields.identification.error': 'Ya existe una cuenta asociada a este DNI o CE',
};

export default signUp;
