const signUp = {
	'left.titlePrefix': 'AHORA,',
	'left.title.toYouOrSomeoneElse': 'Estás a unos pasos de agendar una cita',
	'left.title.guest': 'Estás a unos pasos de agendar una cita',
	'left.title.minor': 'Creación de perfil',
	'left.step.first.label': 'Información del Paciente',
	'left.step.second.label': 'DATOS MÉDICOS',
	'left.step.third.label': 'CONTACTO',
	// About Me
	'aboutme.title.firstSection': 'Completa los',
	'aboutme.title.secondSection': 'datos del paciente',
	'aboutme.title.secondSection.minor': 'datos del menor de edad',
	'aboutme.title.thirdSection': 'para continuar',
	'aboutme.subTitle.forMe': 'Datos personales',
	'aboutme.subTitle.forSomeoneElse': 'Datos personales',
	'aboutme.subTitle.minor': 'Datos personales',
	'aboutme.fields.name.label': 'Nombre del paciente',
	'aboutme.fields.name.label.minor': 'Nombre del menor',
	'aboutme.fields.lastName.label': 'Apellido paterno del paciente',
	'aboutme.fields.lastName.label.minor': 'Apellido paterno del menor',
	'aboutme.fields.secondSurname.label': 'Apellido materno del paciente',
	'aboutme.fields.secondSurname.label.minor': 'Apellido materno del menor',
	'aboutme.fields.birthDate.label': 'Nacimiento',
	'aboutme.fields.birthDate.label.minor': 'Nacimiento del menor',
	'aboutme.fields.birthDate.placeholder': 'DD/MM/AAAA',
	'aboutme.fields.gender.label': 'Sexo',
	'aboutme.fields.gender.label.minor': 'Sexo del menor',
	'aboutme.fields.gender.placeholder': 'Selecciona tu género',
	'aboutme.fields.documenttype.label.minor': 'Tipo de documento',
	'aboutme.fields.document.label.minor': 'DNI o CE del menor',
	'aboutme.fields.documentIssueDate.label.minor': 'Fecha de emisión del DNI del menor:',
	'aboutme.validation.name.required': 'El nombre es obligatorio',
	'aboutme.validation.lastName.required': 'El apellido paterno es obligatorio',
	'aboutme.validation.secondSurname.required': 'El apellido materno es obligatorio',
	'aboutme.validation.birthDate.required': 'La fecha de nacimiento es obligatoria',
	'aboutme.validation.gender.required': 'El sexo es obligatorio',
	'aboutme.validation.document.required': 'El DNI o CE es obligatorio',
	'aboutme.validation.documentIssueDate.required': 'La fecha de emisión es obligatoria',
	'aboutme.privacyPolicy.firstSection': 'Estoy de acuerdo con la',
	'aboutme.privacyPolicy.secondSection': 'política de privacidad',
	'aboutme.submit.text': 'Continuar',
	// Medical data
	'medicalData.mobile.title.firstSection': 'Completa esta información médica',
	'medicalData.title.firstSection': 'Completa esta',
	'medicalData.title.secondSection': 'información médica básica',
	'medicalData.title.thirdSection': 'sobre el',
	'medicalData.title.fourthSection': 'paciente para que el doctor te pueda atender mejor.',
	'medicalData.title.fourthSection.minor': 'menor para que el doctor te pueda atender mejor.',
	'medicalData.subTitle': '2. DATOS MÉDICOS',
	'medicalData.subTitle.minor': '2. DATOS MÉDICOS DEL MENOR',
	'medicalData.fields.consultReason.label': '¿Cuál es el motivo de su consulta?',
	'medicalData.fields.symptom.label': '¿Desde cuándo presenta los síntomas?',
	'medicalData.fields.takeMedicines.label': '¿El paciente está tomando algún medicamento?',
	'medicalData.fields.medicineList.label': 'Menciona los medicamentos',
	'medicalData.fields.haveAllergies.label': '¿Tiene alguna alergia?',
	'medicalData.fields.allergies.label': '¿Qué alergia es?',
	'medicalData.fields.moreInfo.label': '¿Hay algo más que el doctor deba saber?',
	'medicalData.fields.moreInfo.helperText': '¿Tiene alguna condición preexistente o crónica?',
	'medicalData.fields.optional.label': '(opcional)',
	'medicalData.fields.yesOption': 'Sí',
	'medicalData.fields.noOption': 'No',
	'medicalData.fields.files.label.firstPart': 'Adjunta fotos o exámenes realizados',
	'medicalData.fields.files.label.secondPart': 'aquí',
	'medicalData.validation.consultReason.required': 'Debes completar este campo para continuar',
	'medicalData.validation.takeMedicines.required': 'Responde esta pregunta para continuar',
	'medicalData.validation.medicineList.required': 'Indícale al doctor qué medicamento está tomando',
	'medicalData.validation.haveAllergy.required': 'Responde esta pregunta para continuar',
	'medicalData.validation.allergy.required': 'Indícale al doctor las alergias son',
	'medicalData.privacyPolicy.firstSection': 'Estoy de acuerdo con la',
	'medicalData.privacyPolicy.secondSection': 'política de privacidad',
	'medicalData.submit.text': 'Continuar',
	'medicalData.dropzone.label': 'Adjunta fotos o exámenes realizados (Opcional)',
	// Contact
	'contact.mobile.title': 'Usaremos tus datos de contacto para enviarte la información de tu cita',
	'contact.title.firstLine': 'Usaremos los datos de contacto para',
	'contact.title.secondLine': 'enviar información de la cita',
	'contact.subTitle': '3. DATOS DE CONTACTO',
	'contact.fields.idType.label.toYou': 'Tipo de documento',
	'contact.fields.idType.label.toSomeoneElse': 'Tipo de documento del paciente',
	'contact.fields.id.label.toYou': 'N° Documento',
	'contact.fields.id.label.toSomeoneElse': 'DNI o CE del paciente',
	'contact.fields.phoneNumber.label.toYou': 'Ingresa tu número celular',
	'contact.fields.phoneNumber.label.toSomeoneElse': 'Ingresa el número de celular de contacto',
	'contact.fields.phoneNumber.helperText.toYou': 'Con este número iniciarás sesión en el futuro',
	'contact.fields.phoneNumber.helperText.toSomeoneElse': 'Enviaremos un recordatorio a este celular',
	'contact.fields.email.label.toYou': 'Ingresa tu correo electrónico',
	'contact.fields.email.label.toSomeoneElse': 'Ingresa un correo de contacto',
	'contact.fields.address.label': 'Dirección del paciente',
	'contact.fields.ubigeo.label': 'Distrito / Provincia',
	'contact.fields.address.helperText': 'Con la dirección se emitirá una receta médica válida',
	'contact.fields.email.helperText': 'Enviaremos un recordatorio a este correo',
	'contact.fields.password.label': 'Contraseña',
	'contact.fields.repeatPassword.label': 'Repetir Contraseña',
	'contact.validation.id.required': 'El DNI o CE del paciente es obligatorio',
	'contact.validation.idType.required': 'El tipo de documento del paciente es obligatorio',
	'contact.validation.id.digits': 'Ingrese un DNI o CE valido',
	'contact.validation.phoneNumber.required': 'El número de celular de contacto es obligatorio',
	'contact.validation.password.required': 'Ingresa una contraseña',
	'contact.validation.password.incorrectFormat': 'Usa 6 caracteres o más para tu contraseña',
	'contact.validation.repeatPassword.required': 'La contraseña es obligatoria',
	'contact.validation.repeatPassword.notEqual': 'Las contraseñas no coinciden. Intenta de nuevo',
	'contact.validation.email.required': 'El correo electrónico es obligatorio',
	'contact.validation.email.validEmail': 'Ingrese un correo de contacto valido',
	'contact.validation.isterm.required': 'Se requiere aceptar los términos y condiciones',

	'contact.legalInformation.firstSection': 'Al ingresar estás confirmando que estás de acuerdo con nuestra',

	'contact.legalInformation.firstSection1': 'He leído y acepto los',
	'contact.legalInformation.termsAndConditionsLink1': 'Términos y Condiciones',
	'contact.legalInformation.secondSection1': 'y las',
	'contact.legalInformation.privacyPolicyLink1': 'Política de Privacidad',

	'contact.legalInformation.firstSection2': 'He leído y acepto el',
	'contact.legalInformation.analysisData': 'tratamiento de mis datos personales para fines adicionales',

	'contact.legalInformation.privacyPolicyLink': 'política de privacidad',
	'contact.legalInformation.secondSection': 'y nuestros',
	'contact.legalInformation.termsAndConditionsLink': 'términos y condiciones.',
	'contact.submit.text': 'De acuerdo, deseo ingresar',
	'contact.phoneNumber.error': 'El número que ingresaste es inválido',
	'contact.email.error': 'El email que ingresaste es inválido',
	'contact.fields.identification.error': 'Ya existe una cuenta asociada a este DNI o CE',
	// Get Medical information
	'getMedicalInformation.title': 'Estás a unos pasos de agendar una cita',
	'getMedicalInformation.title.mobile': 'Estás agendando una cita',
	// Create Pediatrics Appointment
	'preferPediatrics.title': 'Dado que el paciente tiene menos de 15 años, recomendamos que se atienda con un pediatra.',
	'preferPediatrics.omitLabel': 'Omitir',
	'preferPediatrics.createPediatricsAppointment': 'Agendar con pediatría',
	// Small SignUp form
	'smallSignUp.title': 'Estás a un paso de agendar una cita',
	'smallSignUp.submit.text': 'De acuerdo, deseo continuar',
	'smallSignUp.lastName.label': 'Apellidos del paciente',
};

export default signUp;
