const signUp = {
	'left.titlePrefix': 'AHORA,',
	'left.title.toYouOrSomeoneElse': 'Creación de cuenta',
	'left.title.guest': 'Continuar como invitado',
	'left.step.first.label': 'CONTACTO',
	'left.step.second.label': 'DATOS MÉDICOS',
	'left.step.third.label': 'SOBRE TI',
	// About Me
	'aboutme.title.firstSection': 'Llena los',
	'aboutme.title.secondSection': 'datos del paciente',
	'aboutme.title.thirdSection': 'para continuar',
	'aboutme.subTitle': '3. INFORMACIÓN SOBRE TI',
	'aboutme.fields.name.label': 'Nombre',
	'aboutme.fields.lastName.label': 'Apellido Paterno',
	'aboutme.fields.secondSurname.label': 'Apellido Materno',
	'aboutme.fields.id.label': 'DNI o CE',
	'aboutme.fields.birthDate.label': 'Fecha de Nacimiento',
	'aboutme.fields.birthDate.placeholder': 'DD/MM/AAAA',
	'aboutme.fields.gender.label': 'Género',
	'aboutme.fields.gender.placeholder': 'Selecciona tu género',
	'aboutme.validation.name.required': 'El nombre es obligatorio',
	'aboutme.validation.lastName.required': 'El apellido paterno es obligatorio',
	'aboutme.validation.secondSurname.required': 'El apellido materno es obligatorio',
	'aboutme.validation.id.required': 'El DNI o CE es obligatorio',
	'aboutme.validation.id.digits': 'Ingrese un DNI o CE valido',
	'aboutme.validation.birthDate.required': 'Selecciona una fecha de nacimiento para continuar',
	'aboutme.validation.gender.required': 'Selecciona un género para continuar',
	'aboutme.privacyPolicy.firstSection': 'Estoy de acuerdo con la',
	'aboutme.privacyPolicy.secondSection': 'política de privacidad',
	'aboutme.submit.text': 'De acuerdo, crear mi cuenta',
	'aboutMe.fields.identification.error': 'Ya existe una cuenta asociada a este DNI',
	// Medical data
	'medicalData.mobile.title.firstSection': 'Completa esta información médica',
	'medicalData.title.firstSection': 'Completa esta',
	'medicalData.title.secondSection': 'información médica básica',
	'medicalData.title.thirdSection': 'para que el doctor te pueda atender mejor.',
	'medicalData.subTitle': '2. DATOS MÉDICOS',
	'medicalData.fields.takeMedicines.label': '¿Toma algún medicamento?',
	'medicalData.fields.medicineList.label': '¿Qué medicamentos?',
	'medicalData.fields.haveAllergies.label': '¿Tiene alguna alergia?',
	'medicalData.fields.allergies.label': '¿Qué alergia es?',
	'medicalData.fields.moreInfo.label': '¿Hay algo más que el doctor deba saber?',
	'medicalData.fields.optional.label': '(opcional)',
	'medicalData.fields.yesOption': 'Sí',
	'medicalData.fields.noOption': 'No',
	'medicalData.validation.takeMedicines.required': 'Responde esta pregunta para continuar',
	'medicalData.validation.medicineList.required': 'Indícale al doctor qué medicamento está tomando',
	'medicalData.validation.haveAllergy.required': 'Responde esta pregunta para continuar',
	'medicalData.validation.allergy.required': 'Indícale al doctor las alergias son',
	'medicalData.privacyPolicy.firstSection': 'Estoy de acuerdo con la',
	'medicalData.privacyPolicy.secondSection': 'política de privacidad',
	'medicalData.submit.text': 'Continuar',
	// Contact
	'contact.mobile.title': 'Usaremos tus datos de contacto para enviarte la información de tu cita',
	'contact.title': 'Usaremos los datos de contacto para enviar la información de cita',
	'contact.subTitle': '1. DATOS DE CONTACTO',
	'contact.fields.phoneNumber.label': 'Celular',
	'contact.fields.phoneNumber.helperText': 'Con este número iniciarás sesión en el futuro',
	'contact.fields.email.label': 'Correo electrónico',
	'contact.fields.email.helperText': 'Enviaremos un recordatorio a este correo',
	'contact.fields.password.label': 'Contraseña',
	'contact.fields.repeatPassword.label': 'Repetir Contraseña',
	'contact.validation.phoneNumber.required': 'Debes ingresar un número de celular',
	'contact.validation.password.required': 'Ingresa una contraseña',
	'contact.validation.password.incorrectFormat': 'Usa 6 caracteres o más para tu contraseña',
	'contact.validation.repeatPassword.required': 'Ingresa una contraseña',
	'contact.validation.repeatPassword.notEqual': 'Las contraseñas no coinciden. Intenta de nuevo',
	'contact.validation.email.validEmail': 'Ingrese un correo valido',
	'contact.legalInformation.firstSection': 'Al crear una cuenta estás confirmando que estás de acuerdo con nuestra',
	'contact.legalInformation.privacyPolicyLink': 'política de privacidad',
	'contact.legalInformation.secondSection': 'y nuestros',
	'contact.legalInformation.termsAndConditionsLink': 'términos y condiciones.',
	'contact.submit.text.mobile': 'Continuar',
	'contact.submit.text': 'Continuar',
	'contact.phoneNumber.error': 'El número que ingresaste es inválido',
	'contact.email.error': 'El email que ingresaste es inválido',
};

export default signUp;
