const confirmationL18n = {
	'confirmation.left.prefix': '¡FELICITACIONES!',
	'confirmation.left.title.firstSection': 'Tienes una cita el',
	'confirmation.left.title.secondSection': 'el',
	'confirmation.left.title.thirdSection': 'a las',
	'confirmation.left.patient.title': 'PARA PACIENTE',
	'confirmation.left.doctor.title': 'DOCTOR',
	'confirmation.left.doctor.cmp': 'CMP:',
	'confirmation.right.title': 'TIPS PARA UNA CITA EXITOSA:',
	'confirmation.right.before.title': 'ANTES',
	'confirmation.right.before.messageUnlogged':
		'Entra al enlace de la videollamada que enviaremos a tu correo. Si deseas, puedes copiar y guardar el enlace ahora:',
	'confirmation.right.before.copyLink': 'Copiar',
	'confirmation.right.before.messageWhatsapp': ' o al Whatsapp ',
	'confirmation.right.before.messageLogged':
		'Accede al enlace de la videollamada que enviaremos a tu correo. Si este no llega luego de 10 mínutos, contáctanos a',
	'confirmation.right.during.title': 'DURANTE',
	'confirmation.right.during.message':
		'El Doctor te esperará por 5 minutos, procura estar antes para confirmar tu conexión.',
	'confirmation.right.after.title': 'DESPUÉS',
	'confirmation.right.after.message': 'Al finalizar la consulta, recibirás un resúmen a ',
	'confirmation.right.profileButton': 'Ir a mi panel',
	'confirmation.right.profileLink': 'Ingresa a tu perfil en Alivia. ',
	'confirmation.right.goodbye.message': 'Hasta entonces, cuídate mucho.',
	'confirmation.createPassword.title.firstPart': 'Guarda tus datos',
	'confirmation.createPassword.title.secondPart': 'para tu siguiente visita.',
	'confirmation.bottomMessage.title': 'GUARDA TU INFORMACIÓN Y...',
	'confirmation.bottomMessage.title.forSomeone': 'VINCULA A {{name}} A TU CUENTA',
	'confirmation.bottomMessage.body': 'Accede a tus recetas, historias médicas y mantén el control de tus citas.',
	'confirmation.bottomMessage.body.forSomeone': 'Y podrás ver y gestionar su información, además de otros beneficios.',
	'confirmation.bottomMessage.link': 'MÁS INFO.',
	'dashboard.default.title.firstPart': '{{loggedUserName}}, ¿deseas',
	'dashboard.default.title.secondPart': 'vincular a {{name}} a tu cuenta?',
	'dashboard.default.underAge.disclaimer':
		'Para hacerlo, debes tener una relación de pareteneso directo con {{name}}. Es decir, debe ser tu hijo/a.',
	'dashboard.default.subTitle': 'Beneficios de vincularlo a tu cuenta',
	'dashboard.default.benefits.medicHistory': 'Accede a su historia médica, incluyendo sus tratamientos.',
	'dashboard.default.benefits.appointments': 'Podrás ver las citas que ha agendado.',
	'dashboard.default.benefits.easierNewAppointments': 'Agéndale citas sin ingresar todos sus datos nuevamente.',
	'dashboard.default.privacyPolicies.firstPart':
		'Al hacer click en “Vincular a mi cuenta,” confirmas que tú eres el padre o tutor legal del niño y aceptas nuestra',
	'dashboard.default.privacyPolicies.secondPart': 'política de privacidad',
	'dashboard.default.privacyPolicies.thirdPart': 'y nuestros',
	'dashboard.default.privacyPolicies.fourthPart': 'términos y condiciones',
	'dashboard.default.linkAccountLabel': 'VINCULAR A MI CUENTA',
	'confirmation.linkedAccount.title': '{{name}} se ha vinculado exítosamente a tu cuenta',
	'confirmation.linkedAccount.redirect': 'Continuar a mi cuenta',
};

export default confirmationL18n;
